language: java
jdk: oraclejdk7
before_install:
    # Install base Android SDK
    - sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
    - cat android-sdk-installer | bash /dev/stdin --install=build-tools-18.1.0,android-17,sysimg-17
    - source ~/.android-sdk-installer/env

    # Create and start emulator
    - echo no | android create avd --force -n test -t android-17 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &

script:
    - ./wait_for_emulator
